=== TAKETODAY/today-infrastructure/infra-build/infra-maven-plugin/src/main/resources/cn/taketoday/infra/maven/layers.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  ~ Copyright 2012 - 2023 the original author or authors.
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see [http://www.gnu.org/licenses/]
  -->

<xsd:schema elementFormDefault="qualified"
    xmlns="http://www.springframework.org/schema/boot/layers"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.springframework.org/schema/boot/layers">
  <xsd:element name="layers" type="layersType" />
  <xsd:complexType name="layersType">
    <xsd:sequence>
      <xsd:element name="application" type="applicationType" minOccurs="0" />
      <xsd:element name="dependencies" type="dependenciesType" minOccurs="0" />
      <xsd:element name="layerOrder" type="layerOrderType" minOccurs="0" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="applicationType">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
	The 'into layer' selections that should be applied to application classes and resources.
				]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="into" type="intoType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="dependenciesType">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
	The 'into layer' selections that should be applied to dependencies.
				]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="into" type="dependenciesIntoType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="layerOrderType">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
	The order that layers should be added (starting with the least frequently changed layer).
				]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="layer" maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation><![CDATA[
	The layer name.
				]]></xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="intoType">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element type="xsd:string" name="include"
          minOccurs="0" maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation><![CDATA[
	Pattern of the elements to include.
			]]></xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element type="xsd:string" name="exclude"
          minOccurs="0" maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation><![CDATA[
	Pattern of the elements to exclude.
			]]></xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:choice>
    <xsd:attribute type="xsd:string" name="layer"
        use="required" />
  </xsd:complexType>
  <xsd:complexType name="dependenciesIntoType">
    <xsd:complexContent>
      <xsd:extension base="intoType">
        <xsd:choice minOccurs="0">
          <xsd:element type="xsd:string" name="includeModuleDependencies" minOccurs="0">
            <xsd:annotation>
              <xsd:documentation><![CDATA[
	Include dependencies on other modules in the build.
							]]></xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element type="xsd:string" name="excludeModuleDependencies" minOccurs="0">
            <xsd:annotation>
              <xsd:documentation><![CDATA[
	Exclude dependencies on other modules in the build.
							]]></xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:choice>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

</xsd:schema>

=== TAKETODAY/today-infrastructure/infra-build/infra-maven-plugin/src/test/resources/layers.xml
<!--
  ~ Copyright 2017 - 2023 the original author or authors.
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see [http://www.gnu.org/licenses/]
  -->

<layers xmlns="http://www.springframework.org/schema/boot/layers"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/boot/layers
					  layers.xsd">
  <application>
    <into layer="my-resources">
      <include>META-INF/resources/**</include>
      <exclude>*.properties</exclude>
    </into>
    <into layer="configuration">
      <include>**/application*.*</include>
    </into>
    <into layer="application" />
  </application>
  <dependencies>
    <into layer="snapshot-dependencies">
      <include>*:*:*-SNAPSHOT</include>
      <excludeModuleDependencies />
    </into>
    <into layer="application">
      <includeModuleDependencies />
    </into>
    <into layer="my-deps">
      <include>com.acme:*</include>
    </into>
    <into layer="my-dependencies-name" />
  </dependencies>
  <layerOrder>
    <layer>my-deps</layer>
    <layer>my-dependencies-name</layer>
    <layer>snapshot-dependencies</layer>
    <layer>my-resources</layer>
    <layer>configuration</layer>
    <layer>application</layer>
  </layerOrder>
</layers>
