=== TAKETODAY/today-infrastructure/today-web/src/main/resources/web-configuration-4.0.dtd
<!--
  - Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
  - Copyright Â© TODAY & 2017 - 2023 All Rights Reserved.
  -
  - DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
  -
  - This program is free software: you can redistribute it and/or modify
  - it under the terms of the GNU General Public License as published by
  - the Free Software Foundation, either version 3 of the License, or
  - (at your option) any later version.
  -
  - This program is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  - GNU General Public License for more details.
  -
  - You should have received a copy of the GNU General Public License
  - along with this program.  If not, see [http://www.gnu.org/licenses/]
  -->

<!--
<!DOCTYPE Web-Configuration PUBLIC
		"-//TODAY BLOG//Web-View Configuration DTD 4.0//CN"
			"https://taketoday.cn/framework/web/dtd/web-configuration-4.0.dtd">
-->

<!ELEMENT Web-Configuration (#PCDATA|controller)*>

<!ELEMENT controller (action)*>
	<!ATTLIST controller
		prefix CDATA "/WEB-INF/ftl"
		suffix CDATA ".ftl"
	>

<!ELEMENT action (#PCDATA)>
	<!ATTLIST action
		name CDATA #REQUIRED
		status CDATA #IMPLIED
		resource CDATA #IMPLIED
		content-type CDATA "text/html;charset=UTF-8"
		type (forward|redirect) #IMPLIED
	>

=== TAKETODAY/today-infrastructure/today-framework/src/test/resources/view-controller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
  ~ Copyright Â© TODAY & 2017 - 2023 All Rights Reserved.
  ~
  ~ DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see [http://www.gnu.org/licenses/]
  -->

<!DOCTYPE Web-Configuration PUBLIC
    "-//TODAY BLOG//Web - Configuration DTD 2.0//CN"
    "web-configuration-4.0.dtd">

<!--
    "https://taketoday.cn/framework/web/dtd/web-configuration-2.2.3.dtd">
-->
<Web-Configuration>

  <controller prefix="/error/">
    <action resource="400" name="BadRequest" status="400" />
    <action resource="403" name="Forbidden" status="403" />
    <action resource="404" name="NotFound" status="404" />
    <action resource="500" name="ServerIsBusy" status="500" />
    <action resource="405" name="MethodNotAllowed" status="405" />
  </controller>

  <controller>
    <action resource="redirect:http://pipe.b3log.org/blogs/Today" name="today-blog-pipe" />
    <action resource="redirect:https://taketoday.cn" name="today" />
    <action resource="redirect:https://github.com" name="github" />
    <action resource="redirect:/login" name="login.do" />
  </controller>

  <controller prefix="/xml/">
    <action name="test" resource="test" type="forward" />
  </controller>

</Web-Configuration>

=== TAKETODAY/today-infrastructure/integration-tests/src/test/resources/web-mvc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2017 - 2024 the original author or authors.
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program. If not, see [https://www.gnu.org/licenses/]
  -->

<!DOCTYPE Web-Configuration PUBLIC
        "-//TODAY BLOG//Web-View Configuration DTD 4.0//CN"
        "https://taketoday.cn/framework/web/dtd/web-configuration-4.0.dtd">

<Web-Configuration>

  <controller prefix="/error/">
    <action resource="400" name="BadRequest" status="400" />
    <action resource="403" name="Forbidden" status="403" />
    <action resource="404" name="NotFound" status="404" />
    <action resource="500" name="ServerIsBusy" status="500" />
    <action resource="405" name="MethodNotAllowed" status="405" />
  </controller>

  <controller>
    <action resource="redirect:https://taketoday.cn" name="today" />
    <action resource="redirect:https://github.com" name="github" />
    <action resource="redirect:/login" name="login.do" />
  </controller>

  <controller prefix="/xml/">
    <action name="test" resource="test" type="forward" />
  </controller>

</Web-Configuration>
